apiVersion: v1
kind: Secret
metadata:
  name: {{ include "idsvr-config-params.fullname" . }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    {{- include "idsvr-config-params.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range .Values.configParameters}}
  {{ .key }}: {{.value | b64enc }}
  {{- end}}