apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "application-secrets.fullname" . }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
spec:
  backendType: secretsManager
  data:
  {{- range .Values.secrets}}
  - key: {{ . }}
    name: {{ . }}
  {{- end}}