# Default values for node-local-dns.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: k8s.gcr.io/dns/k8s-dns-node-cache
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 1.21.1
  args:
    interfaceName: nodelocaldns
    healthPort: 8080
    skipTeardown: true
    syncInterval: 1ns
#    setupIptables: false
#    setupEbtables: false
#    quiet: false

dnsUpstreamName: kube-dns-upstream

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
namespace: kube-system

config:
  localDnsIp: 169.254.20.11
  dnsServerIp: 172.20.0.10
  zones:
    - zone: cluster.local:53
      plugins:
        errors: true
        reload: true
        debug: false
        log:
          format: combined
          classes: all
        cache:
          parameters: ""
          denial:
            size: 9984
            ttl: 5
          success:
            size: 9984
            ttl: 30
          prefetch: {}
            # amount: 1
            # duration: 10m
            # percentage: 20%
          serve_stale: false
        forward:
          parameters: __PILLAR__CLUSTER__DNS__
          force_tcp: true
          prefer_udp: false
          policy: "" # random|round_robin|sequential
          max_fails: "" # 10
          expire: "" # 10s
          health_check: "" # 10s
        prometheus: true
        health:
          port: 8080
    - zone: .:53
      plugins:
        errors: true
        reload: true
        debug: false
        log:
          format: combined
          classes: all
        cache:
          parameters: 30
          denial: {}
            # size: 0
            # ttl: 1
          success: {}
            # size: 8192
            # ttl: 30
          prefetch: {}
            # amount: 1
            # duration: 10m
            # percentage: 20%
          serve_stale: false
        forward:
          parameters: __PILLAR__UPSTREAM__SERVERS__ # defaults to /etc/resolv.conf
          force_tcp: false
        prometheus: true
    - zone: ip6.arpa:53
      plugins:
        errors: true
        reload: true
        debug: false
        log:
          format: combined
          classes: all
        cache:
          parameters: 30
        forward:
          parameters: __PILLAR__CLUSTER__DNS__
          force_tcp: true
        prometheus: true
    - zone: in-addr.arpa:53
      plugins:
        errors: true
        reload: true
        debug: false
        log:
          format: combined
          classes: all
        cache:
          parameters: 30
        forward:
          parameters: __PILLAR__CLUSTER__DNS__
          force_tcp: true
        prometheus: true

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

useHostNetwork: true

updateStrategy:
  rollingUpdate:
    maxUnavailable: 10%

priorityClassName: system-node-critical

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  privileged: true

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


nodeSelector: {}

tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoExecute
    operator: Exists
  - effect: NoSchedule
    operator: Exists

affinity: {}

metrics:
  prometheusScrape: "true"
  port: 9253

dns-upstream:
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "KubeDNSUpstream"
  selectorLabels:
    k8s-app: kube-dns
