# Default values for idsvr-config-params.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: ""
nameOverride: ""

namespace: ""

configParameters: []
